## 3 step of juicer
	# 1 data preccessing, mapping the clean data to genome,
	#   characterize the valid pairs and generate a .hic file
	# 2 read the .hic file and create the interactive visulised graph called contact map and scaler to one
	# 3 using the algorithm to predict the TAD and chromatin structure

############# combind Hic-pro and juicer_tools ##############
## 1 prepare .hic file, change the Hic-pro pipline file ValidPairs into .hic
python Hicpro2hic.py -o outdir -s sample -v sample.ValidPairs -g chrom_hg19.sizes -j juicer_tools.jar -r MboI_resfrag_hg19.bed
	# -o outputdir
	# -s output prefix name
	# -v the validpairs generated by hic-pro
	# -g genome chr length
	# -j path of juicer_tools
	# -r enzyme cut info
## 2 Hiccups Call Loops
juicer_tools hiccups [-m matrixSize] [-k normalization (NONE/VC/VC_SQRT/KR)] [-c chromosome(s)] [-r resolutions] [-f fdr] [-p peak width]  \
	[-i window] [-t threshold] [-d centroid distances] \
	[--ignore-sparsity]<hicfile> <output dir> [specified_loop_list]
	## -cpu the cpu version juicer must use this parameter
## Result expounds
##  merged_loops.bedpe contain the merged loops result, each line is a loop info 


##3 Aggregate Peak Analysis
apa [-n minval] [-x maxval] [-w window] [-r resolution(s)] [-c chromosomes]
    [-k NONE/VC/VC_SQRT/KR] [-q corner_width] [-e includchr] [-u save_all_data] <hicFile(s)> <PeakFile> <SaveFolder>
	## hicFile : .hic generate by juicer
	## 
	## PeaksFile standard loop list file such as merged_loops.bedge

	
